neo4j:
  name: "neo4j"
  resources:
    cpu: "0.5"
    memory: "2Gi"
  password: "hamzaboubnane"
  edition: "enterprise"
  acceptLicenseAgreement: "yes"

volumes:
  data:
    mode: "dynamic"
    dynamic:
     # gp2 is a general-purpose SSD volume
     storageClassName: gp2