apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc
  labels:
    app.kubernetes.io/name: "neo4j"
    app.kubernetes.io/instance: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp3-delete-sc