apiVersion: v1
kind: Service
metadata:
  name: "neo4j-admin"
  labels:
    app.kubernetes.io/name: "neo4j"
    app.kubernetes.io/instance: "neo4j"
    app.kubernetes.io/service: "admin"    
spec:
  publishNotReadyAddresses: true
  type: "ClusterIP"
  selector:
    app: "neo4j"
    helm.neo4j.com/instance: "neo4j"
  ports:
    - protocol: TCP
      port: 6362
      targetPort: 6362
      name: tcp-backup
    - protocol: TCP
      port: 7687
      targetPort: 7687
      name: tcp-bolt
    - protocol: TCP
      port: 7474
      targetPort: 7474
      name: tcp-http
    - protocol: TCP
      port: 7473
      targetPort: 7473
      name: tcp-https