apiVersion: v1
kind: Service
metadata:
  name: "neo4j"
  labels:
    app.kubernetes.io/service: "default"
    app.kubernetes.io/name: "neo4j"
    app.kubernetes.io/instance: "neo4j"    
spec:
  publishNotReadyAddresses: false
  type: ClusterIP
  selector:
    app: "neo4j"
    app.kubernetes.io/instance: "neo4j"
  ports:
    - protocol: TCP
      port: 7687
      targetPort: 7687
      name: tcp-bolt
    - protocol: TCP
      port: 7474
      targetPort: 7474
      name: tcp-http
    - protocol: TCP
      port: 7473
      targetPort: 7473
      name: tcp-https